version: "3"
services:
  training:
    build: ./train_model
    environment:
      - SO=docker
    volumes:
      - ./train_model/model:/code/model
    command: python service.py
    #ports:
    #  - "8887:8887"

  backend:
    build: ./backend
    volumes:
      - ./train_model/model:/model
      - ./train_model/model/data_train:/data_train
      #- ./backend/src:/code
    command: python api.py
    #ports:
    #  - "8000:8000"
    depends_on:
      - training

  # http://localhost:8888/
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/code
      - ./train_model/model:/code/model
      - ./user_data/nuevos_chats:/nuevos_chats
      - ./user_data/received_files:/received_files
    environment:
      - SO=docker
    ports:
      - "8888:8888"
    depends_on:
      - backend
      - training
    command: python app.py

  telegram_connector:
    build: ./telegram_connect
    volumes:
      - ./telegram_connect/src:/code
      - ./telegram_connect/chats:/code/chats
    environment:
      - SO=docker
    depends_on:
      - backend
      - frontend
    command: python connection_bot_telegram.py