version: "3"
services:
  backend:
    build: .
    volumes:
      - ./src/model:/code/model
      - ./src/model/data_train:/code/model/data_train
      - ./src:/code
    environment:
      - SO=docker
    ports:
      - "8887:80"
